# Generated by Django 2.2.3 on 2019-07-11 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PayMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payed_by', models.CharField(max_length=100, verbose_name='cost payed by')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=5, max_digits=20)),
                ('purchase_date', models.DateTimeField(verbose_name='purchased date')),
                ('description', models.CharField(max_length=1000, verbose_name='Extra notes on the purchase')),
                ('entered_date', models.DateTimeField(verbose_name='data added date')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenseapp.Category')),
                ('payed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenseapp.PayMode')),
                ('shop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenseapp.Shop')),
            ],
        ),
    ]
