# Generated by Django 2.2.3 on 2019-07-30 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0003_auto_20190730_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenseapp.Category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenseapp.PayMode'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenseapp.Shop'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.UserProfileInfo'),
        ),
    ]
