# Generated by Django 2.2.3 on 2019-07-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0004_auto_20190730_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='quantity',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='rate',
            field=models.CharField(max_length=20),
        ),
    ]
