# Generated by Django 2.2.3 on 2019-07-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0006_auto_20190730_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Extra notes on the purchase'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='rate',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
    ]
